/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import dctw.Agent1;
import dctw.AgentInitiateur;
import dctw.Localisation;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DJAWED
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aside = new javax.swing.JPanel();
        jPanel_initiateur = new javax.swing.JPanel();
        jLabel_Agent_Initiateur = new javax.swing.JLabel();
        jPanel_Agent1 = new javax.swing.JPanel();
        jLabel_Agent1 = new javax.swing.JLabel();
        jPanel_Agent2 = new javax.swing.JPanel();
        Agent2 = new javax.swing.JLabel();
        Jpanel_Agent3 = new javax.swing.JPanel();
        Label_Agent3 = new javax.swing.JLabel();
        jPanel_Agent4 = new javax.swing.JPanel();
        jLabel_Agent4 = new javax.swing.JLabel();
        jPanel_Principale = new javax.swing.JPanel();
        jPanel_Initiateur = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Matrice_Performance = new javax.swing.JTable();
        JButton_Envoie_Performance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Agents = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Rangement = new javax.swing.JTable();
        jLabel_Agents = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(877, 500));

        Aside.setBackground(new java.awt.Color(102, 255, 255));
        Aside.setMinimumSize(new java.awt.Dimension(90, 80));
        Aside.setPreferredSize(new java.awt.Dimension(200, 80));
        Aside.setLayout(new java.awt.GridLayout(5, 0));

        jPanel_initiateur.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_initiateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_initiateurMousePressed(evt);
            }
        });
        jPanel_initiateur.setLayout(new java.awt.BorderLayout());

        jLabel_Agent_Initiateur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Agent_Initiateur.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Agent_Initiateur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Agent_Initiateur.setText("Agent initiateur");
        jLabel_Agent_Initiateur.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Agent_Initiateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_Agent_InitiateurMousePressed(evt);
            }
        });
        jPanel_initiateur.add(jLabel_Agent_Initiateur, java.awt.BorderLayout.CENTER);

        Aside.add(jPanel_initiateur);

        jPanel_Agent1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Agent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_Agent1MousePressed(evt);
            }
        });
        jPanel_Agent1.setLayout(new java.awt.BorderLayout());

        jLabel_Agent1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Agent1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Agent1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Agent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Agent1.setText("Agent 1");
        jLabel_Agent1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Agent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_Agent1MousePressed(evt);
            }
        });
        jPanel_Agent1.add(jLabel_Agent1, java.awt.BorderLayout.CENTER);

        Aside.add(jPanel_Agent1);

        jPanel_Agent2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Agent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_Agent2MousePressed(evt);
            }
        });
        jPanel_Agent2.setLayout(new java.awt.BorderLayout());

        Agent2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agent2.setForeground(new java.awt.Color(0, 0, 0));
        Agent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Agent2.setText("Agent 2");
        Agent2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Agent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Agent2MousePressed(evt);
            }
        });
        jPanel_Agent2.add(Agent2, java.awt.BorderLayout.CENTER);

        Aside.add(jPanel_Agent2);

        Jpanel_Agent3.setBackground(new java.awt.Color(255, 255, 255));
        Jpanel_Agent3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Jpanel_Agent3MousePressed(evt);
            }
        });
        Jpanel_Agent3.setLayout(new java.awt.BorderLayout());

        Label_Agent3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Agent3.setForeground(new java.awt.Color(0, 0, 0));
        Label_Agent3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Agent3.setText("Agent 3");
        Label_Agent3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Label_Agent3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Label_Agent3MousePressed(evt);
            }
        });
        Jpanel_Agent3.add(Label_Agent3, java.awt.BorderLayout.CENTER);

        Aside.add(Jpanel_Agent3);

        jPanel_Agent4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Agent4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_Agent4MousePressed(evt);
            }
        });
        jPanel_Agent4.setLayout(new java.awt.BorderLayout());

        jLabel_Agent4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Agent4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Agent4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Agent4.setText("Agent 4");
        jLabel_Agent4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Agent4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_Agent4MousePressed(evt);
            }
        });
        jPanel_Agent4.add(jLabel_Agent4, java.awt.BorderLayout.CENTER);

        Aside.add(jPanel_Agent4);

        getContentPane().add(Aside, java.awt.BorderLayout.LINE_START);

        jPanel_Principale.setLayout(new java.awt.CardLayout());

        jPanel_Initiateur.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Initiateur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Matrice_Performance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Matrice_Performance.setPreferredSize(new java.awt.Dimension(100, 80));
        jScrollPane1.setViewportView(jTable_Matrice_Performance);

        jPanel_Initiateur.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 510, 260));

        JButton_Envoie_Performance.setText("Envoyer matrice de performance");
        JButton_Envoie_Performance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_Envoie_PerformanceActionPerformed(evt);
            }
        });
        jPanel_Initiateur.add(JButton_Envoie_Performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 210, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Matrice de performance");
        jPanel_Initiateur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 290, 30));

        jPanel_Principale.add(jPanel_Initiateur, "card2");

        jPanel_Agents.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Agents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Rangement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Rangement);

        jPanel_Agents.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 500, 260));

        jLabel_Agents.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Agents.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Agents.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Agents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Agents.setText("jLabel2");
        jPanel_Agents.add(jLabel_Agents, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 230, 40));

        jPanel_Principale.add(jPanel_Agents, "card3");

        getContentPane().add(jPanel_Principale, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Agent_InitiateurMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agent_InitiateurMousePressed
        dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Initiateur);
    }//GEN-LAST:event_jLabel_Agent_InitiateurMousePressed

    private void jPanel_initiateurMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_initiateurMousePressed
        dctw.Fucnction.ChangePanel(jPanel_Agents,jPanel_Initiateur);
    }//GEN-LAST:event_jPanel_initiateurMousePressed

    private void jLabel_Agent1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agent1MousePressed
        dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 1");
    }//GEN-LAST:event_jLabel_Agent1MousePressed

    private void jPanel_Agent1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Agent1MousePressed
        dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 1");
    }//GEN-LAST:event_jPanel_Agent1MousePressed

    private void Agent2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agent2MousePressed
         dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 2");
    }//GEN-LAST:event_Agent2MousePressed

    private void jPanel_Agent2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Agent2MousePressed
       dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 2");
    }//GEN-LAST:event_jPanel_Agent2MousePressed

    private void Label_Agent3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_Agent3MousePressed
        dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 3");
    }//GEN-LAST:event_Label_Agent3MousePressed

    private void Jpanel_Agent3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jpanel_Agent3MousePressed
        dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 3");
    }//GEN-LAST:event_Jpanel_Agent3MousePressed

    private void jLabel_Agent4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agent4MousePressed
         dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 4");
    }//GEN-LAST:event_jLabel_Agent4MousePressed

    private void jPanel_Agent4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Agent4MousePressed
       dctw.Fucnction.ChangePanel(jPanel_Principale,jPanel_Agents);
        jLabel_Agents.setText("Agent 4");
    }//GEN-LAST:event_jPanel_Agent4MousePressed

    private void JButton_Envoie_PerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_Envoie_PerformanceActionPerformed
        ArrayList<Localisation> tableau= new ArrayList<>();
        
        tableau.add(new Localisation(1.00,0.99,2,6,1867,10,0.68));
        tableau.add(new Localisation(1.00,0.98,2,6,1957,10,0.71));
        tableau.add(new Localisation(1.00,0.97,2,6,2047,10,0.70));
        tableau.add(new Localisation(0.85,0.97,2,6,2147,10,0.69));
        tableau.add(new Localisation(1.00,0.93,2,6,2233,9,0.67));
        tableau.add(new Localisation(0.50,0.96,2,6,2185,12,0.84));
        tableau.add(new Localisation(1.00,0.67,2,6,2220,9,0.68));
        tableau.add(new Localisation(1.00,0.15,4,6,1832,11,0.71));
        tableau.add(new Localisation(0.99,0.55,4,6,1906,10,0.74));
        tableau.add(new Localisation(0.98,0.27,4,6,2037,10,0.75));
        tableau.add(new Localisation(1.00,0.96,4,6,2232,13,0.86));
        tableau.add(new Localisation(0.95,0.69,4,6,2186,5,0.78));
        tableau.add(new Localisation(1.00,0.62,6,3,1911,10,0.70));
        tableau.add(new Localisation(0.40,1.00,6,3,2070,6,0.85));
        tableau.add(new Localisation(1.00,1.00,6,3,2142,6,0.85));
        tableau.add(new Localisation(1.00,0.98,6,6,1648,10,0.84));
        tableau.add(new Localisation(0.70,0.98,6,6,1756,10,0.68));
        tableau.add(new Localisation(1.00,0.98,6,6,1821,10,0.83));
        
        dctw.AgentInitiateur init= new AgentInitiateur();
        
        
        dctw.Agent1 agent1= new Agent1();
        dctw.AgentInitiateur AgentInitiateur=new AgentInitiateur();
        agent1.recepteur();
        AgentInitiateur.SendMatricePerformance();
        System.out.println("haja srat");
       
    }//GEN-LAST:event_JButton_Envoie_PerformanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agent2;
    private javax.swing.JPanel Aside;
    private javax.swing.JButton JButton_Envoie_Performance;
    private javax.swing.JPanel Jpanel_Agent3;
    private javax.swing.JLabel Label_Agent3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Agent1;
    private javax.swing.JLabel jLabel_Agent4;
    private javax.swing.JLabel jLabel_Agent_Initiateur;
    private javax.swing.JLabel jLabel_Agents;
    private javax.swing.JPanel jPanel_Agent1;
    private javax.swing.JPanel jPanel_Agent2;
    private javax.swing.JPanel jPanel_Agent4;
    private javax.swing.JPanel jPanel_Agents;
    private javax.swing.JPanel jPanel_Initiateur;
    private javax.swing.JPanel jPanel_Principale;
    private javax.swing.JPanel jPanel_initiateur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Matrice_Performance;
    private javax.swing.JTable jTable_Rangement;
    // End of variables declaration//GEN-END:variables
}
